server:
  port: 9080
  serverIp: "127.0.0.1"
  announcedIp: 127.0.0.1
mediasoup:
  numberOfWorkers: 1
  workerSettings:
    logLevel: "warn"
    logTags:
      - "info"
      - "ice"
      - "dtls"
      - "rtp"
      - "srtp"
      - "rtcp"
    rtcMinPort: 40000
    rtcMaxPort: 41000
  mediaCodecs:
    - kind: "audio"
      mimeType: "audio/opus"
      clockRate: 48000
      channels: 2
    - kind: "video"
      mimeType: "video/VP8"
      clockRate: 90000
  # A few things to note:
  # - The number of WebRTC servers created will match the number of entries listed here.
  # - At least one listenInfo must be declared for each webrtc server.
  # - The same port must be used for all listenInfo entries (TCP and UDP).
  # - A single port cannot be shared across multiple webRtcServerSettings.
  # - Use announcedAddress to specify the address that will appear in the SDP if needed.
  # webRtcServerSettings:
  #   - listenInfos:
  #       - ip: 0.0.0.0
  #         protocol: "udp"
  #         port: 5000
  #         announcedAddress: 127.0.0.1
  # - ip: "127.0.0.1"
  #   protocol: "tcp"
  #   port: 5000
  # announcedAddress:
