server:
  port: 9081
  serverIp: "127.0.0.1"
  # announcedIp: "127.0.0.1"

hamok:
  clientsMap:
    mapId: "webrtc-observer-clients-map"
  eventEmitter:
    emitterId: "webrtc-observer-media-service-events"
  roomsMap:
    mapId: "webrtc-observer-rooms-map"
  redis:
    host: "localhost"
    port: 6379
  redisChannelId: "webrtc-observer-hamok-message-channel"
  devMode: true

# stunnerAuthUrl: "http://stunner-auth.stunner-system:8088?service=turn"
maxTransportsPerRouter: 6
maxProducerPerClients: 2
maxClientLifeTimeInMins: 15

mediasoup:
  numberOfWorkers: 1
  workerSettings:
    logLevel: "warn"
    logTags:
      - "info"
      - "ice"
      - "dtls"
      - "rtp"
      - "srtp"
      - "rtcp"
    rtcMinPort: 42000
    rtcMaxPort: 43000
  mediaCodecs:
    - kind: "audio"
      mimeType: "audio/opus"
      clockRate: 48000
      channels: 2
    - kind: "video"
      mimeType: "video/VP8"
      clockRate: 90000
  webRtcServerSettings:
    - listenInfos:
        - ip: "127.0.0.1"
          # ip: "0.0.0.0"
          protocol: "udp"
          # announcedAddress: "127.0.0.1"
          port: 5001
