{
 "title": "STUNner Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Packet Processing Delay",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(stunner_total_packet_latency) / sum(stunner_inbound_packets_total))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average Packet Processing Extra Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(stunner_total_packet_latency) / sum(stunner_inbound_packets_total)",
     "legendFormat": "Average Processing Time"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(stunner_inbound_bytes_total[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "stunner_active_connections", "legendFormat": "__auto" }
   ]
  }
 ]
}